sequenceDiagram
    box ioq3ded.x86_64
        participant q3 as Quake 3
    end
    box qagamex86_64.so
        participant m as Syscalls
        participant s as GameModule
    end

    s->>s: init(...)
    s->>m: error(...)
    m->>m: syscall(G_ERROR, ...)
    m->>q3: VM_DllSyscall(G_ERROR, ...)
    q3->>q3: SV_GameSystemCalls(G_ERROR, ...)
    q3->>q3: Com_Error(...)
