sequenceDiagram
    box ioq3ded.x86_64
        participant q3 as Quake 3
    end
    box qagamex86_64.so
        participant m as game_module!
        participant s as GameModule
    end

    q3->>q3: SV_InitGameVM(restart)
    q3->>q3: VM_Call(GAME_INIT, time, restart, ...)
    q3->>m: vmMain(GAME_INIT, ...)
    m->>m: vm_main(GAME_INIT, ...)
    m->>s: init(time, ...)
